
export class BibleBookMapper {
  private static bookNames: Record<string, string> = {
    // Old Testament
    'genesis': 'Genesis',
    'gen': 'Genesis',
    'exodus': 'Exodus',
    'exo': 'Exodus',
    'leviticus': 'Leviticus',
    'lev': 'Leviticus',
    'numbers': 'Numbers',
    'num': 'Numbers',
    'deuteronomy': 'Deuteronomy',
    'deu': 'Deuteronomy',
    'joshua': 'Joshua',
    'jos': 'Joshua',
    'judges': 'Judges',
    'jdg': 'Judges',
    'ruth': 'Ruth',
    'rut': 'Ruth',
    '1samuel': '1 Samuel',
    '1sa': '1 Samuel',
    '2samuel': '2 Samuel',
    '2sa': '2 Samuel',
    '1kings': '1 Kings',
    '1ki': '1 Kings',
    '2kings': '2 Kings',
    '2ki': '2 Kings',
    '1chronicles': '1 Chronicles',
    '1ch': '1 Chronicles',
    '2chronicles': '2 Chronicles',
    '2ch': '2 Chronicles',
    'ezra': 'Ezra',
    'ezr': 'Ezra',
    'nehemiah': 'Nehemiah',
    'neh': 'Nehemiah',
    'esther': 'Esther',
    'est': 'Esther',
    'job': 'Job',
    'psalms': 'Psalms',
    'psa': 'Psalms',
    'psalm': 'Psalms',
    'proverbs': 'Proverbs',
    'pro': 'Proverbs',
    'ecclesiastes': 'Ecclesiastes',
    'ecc': 'Ecclesiastes',
    'songofsolomon': 'Song of Solomon',
    'sng': 'Song of Solomon',
    'isaiah': 'Isaiah',
    'isa': 'Isaiah',
    'jeremiah': 'Jeremiah',
    'jer': 'Jeremiah',
    'lamentations': 'Lamentations',
    'lam': 'Lamentations',
    'ezekiel': 'Ezekiel',
    'eze': 'Ezekiel',
    'daniel': 'Daniel',
    'dan': 'Daniel',
    'hosea': 'Hosea',
    'hos': 'Hosea',
    'joel': 'Joel',
    'joe': 'Joel',
    'amos': 'Amos',
    'amo': 'Amos',
    'obadiah': 'Obadiah',
    'oba': 'Obadiah',
    'jonah': 'Jonah',
    'jon': 'Jonah',
    'micah': 'Micah',
    'mic': 'Micah',
    'nahum': 'Nahum',
    'nah': 'Nahum',
    'habakkuk': 'Habakkuk',
    'hab': 'Habakkuk',
    'zephaniah': 'Zephaniah',
    'zep': 'Zephaniah',
    'haggai': 'Haggai',
    'hag': 'Haggai',
    'zechariah': 'Zechariah',
    'zec': 'Zechariah',
    'malachi': 'Malachi',
    'mal': 'Malachi',
    
    // New Testament
    'matthew': 'Matthew',
    'mat': 'Matthew',
    'mark': 'Mark',
    'mar': 'Mark',
    'luke': 'Luke',
    'luk': 'Luke',
    'john': 'John',
    'joh': 'John',
    'acts': 'Acts',
    'act': 'Acts',
    'romans': 'Romans',
    'rom': 'Romans',
    '1corinthians': '1 Corinthians',
    '1co': '1 Corinthians',
    '2corinthians': '2 Corinthians',
    '2co': '2 Corinthians',
    'galatians': 'Galatians',
    'gal': 'Galatians',
    'ephesians': 'Ephesians',
    'eph': 'Ephesians',
    'philippians': 'Philippians',
    'phi': 'Philippians',
    'colossians': 'Colossians',
    'col': 'Colossians',
    '1thessalonians': '1 Thessalonians',
    '1th': '1 Thessalonians',
    '2thessalonians': '2 Thessalonians',
    '2th': '2 Thessalonians',
    '1timothy': '1 Timothy',
    '1ti': '1 Timothy',
    '2timothy': '2 Timothy',
    '2ti': '2 Timothy',
    'titus': 'Titus',
    'tit': 'Titus',
    'philemon': 'Philemon',
    'phm': 'Philemon',
    'hebrews': 'Hebrews',
    'heb': 'Hebrews',
    'james': 'James',
    'jam': 'James',
    '1peter': '1 Peter',
    '1pe': '1 Peter',
    '2peter': '2 Peter',
    '2pe': '2 Peter',
    '1john': '1 John',
    '1jo': '1 John',
    '2john': '2 John',
    '2jo': '2 John',
    '3john': '3 John',
    '3jo': '3 John',
    'jude': 'Jude',
    'jud': 'Jude',
    'revelation': 'Revelation',
    'rev': 'Revelation'
  };

  static getBookName(bookKey: string): string {
    const lowerKey = bookKey.toLowerCase();
    return this.bookNames[lowerKey] || bookKey.charAt(0).toUpperCase() + bookKey.slice(1);
  }
}
